// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: debate.proto
// Protobuf C++ Version: 5.29.5

#include "debate.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace debate {

inline constexpr Link::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : connection_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        id_{0},
        connect_from_{0},
        connect_to_{0},
        creator_id_{0},
        link_type_{static_cast< ::debate::LinkType >(0)},
        debate_id_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Link::Link(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct LinkDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LinkDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~LinkDefaultTypeInternal() {}
  union {
    Link _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LinkDefaultTypeInternal _Link_default_instance_;

inline constexpr Debate::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        debater_ids_{},
        _debater_ids_cached_byte_size_{0},
        topic_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        settings_{nullptr},
        id_{0},
        root_claim_id_{0},
        creator_id_{0},
        is_challenge_{false},
        parent_challenge_id_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Debate::Debate(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct DebateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DebateDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DebateDefaultTypeInternal() {}
  union {
    Debate _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DebateDefaultTypeInternal _Debate_default_instance_;

inline constexpr Claim::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : history_{},
        link_ids_{},
        _link_ids_cached_byte_size_{0},
        sentence_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        description_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        id_{0},
        creator_id_{0},
        debate_id_{0},
        status_{static_cast< ::debate::ClaimStatus >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Claim::Claim(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ClaimDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ClaimDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ClaimDefaultTypeInternal() {}
  union {
    Claim _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ClaimDefaultTypeInternal _Claim_default_instance_;

inline constexpr ClaimState::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        claim_{nullptr},
        timestamp_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR ClaimState::ClaimState(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ClaimStateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ClaimStateDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ClaimStateDefaultTypeInternal() {}
  union {
    ClaimState _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ClaimStateDefaultTypeInternal _ClaimState_default_instance_;
}  // namespace debate
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_debate_2eproto[3];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_debate_2eproto = nullptr;
const ::uint32_t
    TableStruct_debate_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::debate::Claim, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::debate::Claim, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::debate::Claim, _impl_.sentence_),
        PROTOBUF_FIELD_OFFSET(::debate::Claim, _impl_.description_),
        PROTOBUF_FIELD_OFFSET(::debate::Claim, _impl_.creator_id_),
        PROTOBUF_FIELD_OFFSET(::debate::Claim, _impl_.debate_id_),
        PROTOBUF_FIELD_OFFSET(::debate::Claim, _impl_.history_),
        PROTOBUF_FIELD_OFFSET(::debate::Claim, _impl_.status_),
        PROTOBUF_FIELD_OFFSET(::debate::Claim, _impl_.link_ids_),
        PROTOBUF_FIELD_OFFSET(::debate::ClaimState, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::debate::ClaimState, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::debate::ClaimState, _impl_.timestamp_),
        PROTOBUF_FIELD_OFFSET(::debate::ClaimState, _impl_.claim_),
        1,
        0,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::debate::Link, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::debate::Link, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::debate::Link, _impl_.connect_from_),
        PROTOBUF_FIELD_OFFSET(::debate::Link, _impl_.connect_to_),
        PROTOBUF_FIELD_OFFSET(::debate::Link, _impl_.connection_),
        PROTOBUF_FIELD_OFFSET(::debate::Link, _impl_.creator_id_),
        PROTOBUF_FIELD_OFFSET(::debate::Link, _impl_.link_type_),
        PROTOBUF_FIELD_OFFSET(::debate::Link, _impl_.debate_id_),
        PROTOBUF_FIELD_OFFSET(::debate::Debate, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::debate::Debate, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::debate::Debate, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::debate::Debate, _impl_.root_claim_id_),
        PROTOBUF_FIELD_OFFSET(::debate::Debate, _impl_.topic_),
        PROTOBUF_FIELD_OFFSET(::debate::Debate, _impl_.debater_ids_),
        PROTOBUF_FIELD_OFFSET(::debate::Debate, _impl_.creator_id_),
        PROTOBUF_FIELD_OFFSET(::debate::Debate, _impl_.settings_),
        PROTOBUF_FIELD_OFFSET(::debate::Debate, _impl_.is_challenge_),
        PROTOBUF_FIELD_OFFSET(::debate::Debate, _impl_.parent_challenge_id_),
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        0,
        ~0u,
        ~0u,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::debate::Claim)},
        {16, 26, -1, sizeof(::debate::ClaimState)},
        {28, -1, -1, sizeof(::debate::Link)},
        {43, 59, -1, sizeof(::debate::Debate)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::debate::_Claim_default_instance_._instance,
    &::debate::_ClaimState_default_instance_._instance,
    &::debate::_Link_default_instance_._instance,
    &::debate::_Debate_default_instance_._instance,
};
const char descriptor_table_protodef_debate_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\014debate.proto\022\006debate\032\037google/protobuf/"
    "timestamp.proto\032\025debate_settings.proto\"\275"
    "\001\n\005Claim\022\n\n\002id\030\001 \001(\005\022\020\n\010sentence\030\002 \001(\t\022\023"
    "\n\013description\030\003 \001(\t\022\022\n\ncreator_id\030\010 \001(\005\022"
    "\021\n\tdebate_id\030\t \001(\005\022#\n\007history\030\n \003(\0132\022.de"
    "bate.ClaimState\022#\n\006status\030\013 \001(\0162\023.debate"
    ".ClaimStatus\022\020\n\010link_ids\030\014 \003(\005\"Y\n\nClaimS"
    "tate\022-\n\ttimestamp\030\002 \001(\0132\032.google.protobu"
    "f.Timestamp\022\034\n\005claim\030\001 \001(\0132\r.debate.Clai"
    "m\"\234\001\n\004Link\022\n\n\002id\030\001 \001(\005\022\024\n\014connect_from\030\002"
    " \001(\005\022\022\n\nconnect_to\030\003 \001(\005\022\022\n\nconnection\030\004"
    " \001(\t\022\022\n\ncreator_id\030\005 \001(\005\022#\n\tlink_type\030\006 "
    "\001(\0162\020.debate.LinkType\022\021\n\tdebate_id\030\007 \001(\005"
    "\"\300\001\n\006Debate\022\n\n\002id\030\001 \001(\005\022\025\n\rroot_claim_id"
    "\030\002 \001(\005\022\r\n\005topic\030\003 \001(\t\022\023\n\013debater_ids\030\004 \003"
    "(\005\022\022\n\ncreator_id\030\005 \001(\005\022(\n\010settings\030\006 \001(\013"
    "2\026.debate.DebateSettings\022\024\n\014is_challenge"
    "\030\007 \001(\010\022\033\n\023parent_challenge_id\030\010 \001(\005*G\n\013C"
    "laimStatus\022\013\n\007NEUTRAL\020\000\022\016\n\nCHALLENGED\020\001\022"
    "\014\n\010DEFENDED\020\002\022\r\n\tDISPROVEN\020\003*7\n\010LinkType"
    "\022\n\n\006NORMAL\020\000\022\020\n\014PARENT_CHILD\020\001\022\r\n\tCHALLE"
    "NGE\020\002*8\n\017ChallengeStatus\022\013\n\007ONGOING\020\000\022\014\n"
    "\010CONCEDED\020\001\022\n\n\006PROVEN\020\002b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_debate_2eproto_deps[2] =
    {
        &::descriptor_table_debate_5fsettings_2eproto,
        &::descriptor_table_google_2fprotobuf_2ftimestamp_2eproto,
};
static ::absl::once_flag descriptor_table_debate_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_debate_2eproto = {
    false,
    false,
    911,
    descriptor_table_protodef_debate_2eproto,
    "debate.proto",
    &descriptor_table_debate_2eproto_once,
    descriptor_table_debate_2eproto_deps,
    2,
    4,
    schemas,
    file_default_instances,
    TableStruct_debate_2eproto::offsets,
    file_level_enum_descriptors_debate_2eproto,
    file_level_service_descriptors_debate_2eproto,
};
namespace debate {
const ::google::protobuf::EnumDescriptor* ClaimStatus_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_debate_2eproto);
  return file_level_enum_descriptors_debate_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t ClaimStatus_internal_data_[] = {
    262144u, 0u, };
bool ClaimStatus_IsValid(int value) {
  return 0 <= value && value <= 3;
}
const ::google::protobuf::EnumDescriptor* LinkType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_debate_2eproto);
  return file_level_enum_descriptors_debate_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t LinkType_internal_data_[] = {
    196608u, 0u, };
bool LinkType_IsValid(int value) {
  return 0 <= value && value <= 2;
}
const ::google::protobuf::EnumDescriptor* ChallengeStatus_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_debate_2eproto);
  return file_level_enum_descriptors_debate_2eproto[2];
}
PROTOBUF_CONSTINIT const uint32_t ChallengeStatus_internal_data_[] = {
    196608u, 0u, };
bool ChallengeStatus_IsValid(int value) {
  return 0 <= value && value <= 2;
}
// ===================================================================

class Claim::_Internal {
 public:
};

Claim::Claim(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:debate.Claim)
}
inline PROTOBUF_NDEBUG_INLINE Claim::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::debate::Claim& from_msg)
      : history_{visibility, arena, from.history_},
        link_ids_{visibility, arena, from.link_ids_},
        _link_ids_cached_byte_size_{0},
        sentence_(arena, from.sentence_),
        description_(arena, from.description_),
        _cached_size_{0} {}

Claim::Claim(
    ::google::protobuf::Arena* arena,
    const Claim& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Claim* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, id_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, id_),
           offsetof(Impl_, status_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::status_));

  // @@protoc_insertion_point(copy_constructor:debate.Claim)
}
inline PROTOBUF_NDEBUG_INLINE Claim::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : history_{visibility, arena},
        link_ids_{visibility, arena},
        _link_ids_cached_byte_size_{0},
        sentence_(arena),
        description_(arena),
        _cached_size_{0} {}

inline void Claim::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, id_),
           0,
           offsetof(Impl_, status_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::status_));
}
Claim::~Claim() {
  // @@protoc_insertion_point(destructor:debate.Claim)
  SharedDtor(*this);
}
inline void Claim::SharedDtor(MessageLite& self) {
  Claim& this_ = static_cast<Claim&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.sentence_.Destroy();
  this_._impl_.description_.Destroy();
  this_._impl_.~Impl_();
}

inline void* Claim::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Claim(arena);
}
constexpr auto Claim::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(Claim, _impl_.history_) +
          decltype(Claim::_impl_.history_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(Claim, _impl_.link_ids_) +
          decltype(Claim::_impl_.link_ids_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(Claim), alignof(Claim), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&Claim::PlacementNew_,
                                 sizeof(Claim),
                                 alignof(Claim));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Claim::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Claim_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Claim::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Claim>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Claim::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Claim>(), &Claim::ByteSizeLong,
            &Claim::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Claim, _impl_._cached_size_),
        false,
    },
    &Claim::kDescriptorMethods,
    &descriptor_table_debate_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Claim::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 8, 1, 48, 2> Claim::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    12, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294963320,  // skipmap
    offsetof(decltype(_table_), field_entries),
    8,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::debate::Claim>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Claim, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(Claim, _impl_.id_)}},
    // string sentence = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(Claim, _impl_.sentence_)}},
    // string description = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(Claim, _impl_.description_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    // int32 creator_id = 8;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Claim, _impl_.creator_id_), 63>(),
     {64, 63, 0, PROTOBUF_FIELD_OFFSET(Claim, _impl_.creator_id_)}},
    // int32 debate_id = 9;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Claim, _impl_.debate_id_), 63>(),
     {72, 63, 0, PROTOBUF_FIELD_OFFSET(Claim, _impl_.debate_id_)}},
    // repeated .debate.ClaimState history = 10;
    {::_pbi::TcParser::FastMtR1,
     {82, 63, 0, PROTOBUF_FIELD_OFFSET(Claim, _impl_.history_)}},
    // .debate.ClaimStatus status = 11;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Claim, _impl_.status_), 63>(),
     {88, 63, 0, PROTOBUF_FIELD_OFFSET(Claim, _impl_.status_)}},
    // repeated int32 link_ids = 12;
    {::_pbi::TcParser::FastV32P1,
     {98, 63, 0, PROTOBUF_FIELD_OFFSET(Claim, _impl_.link_ids_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 id = 1;
    {PROTOBUF_FIELD_OFFSET(Claim, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string sentence = 2;
    {PROTOBUF_FIELD_OFFSET(Claim, _impl_.sentence_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string description = 3;
    {PROTOBUF_FIELD_OFFSET(Claim, _impl_.description_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 creator_id = 8;
    {PROTOBUF_FIELD_OFFSET(Claim, _impl_.creator_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 debate_id = 9;
    {PROTOBUF_FIELD_OFFSET(Claim, _impl_.debate_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // repeated .debate.ClaimState history = 10;
    {PROTOBUF_FIELD_OFFSET(Claim, _impl_.history_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // .debate.ClaimStatus status = 11;
    {PROTOBUF_FIELD_OFFSET(Claim, _impl_.status_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // repeated int32 link_ids = 12;
    {PROTOBUF_FIELD_OFFSET(Claim, _impl_.link_ids_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedInt32)},
  }}, {{
    {::_pbi::TcParser::GetTable<::debate::ClaimState>()},
  }}, {{
    "\14\0\10\13\0\0\0\0\0\0\0\0\0\0\0\0"
    "debate.Claim"
    "sentence"
    "description"
  }},
};

PROTOBUF_NOINLINE void Claim::Clear() {
// @@protoc_insertion_point(message_clear_start:debate.Claim)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.history_.Clear();
  _impl_.link_ids_.Clear();
  _impl_.sentence_.ClearToEmpty();
  _impl_.description_.ClearToEmpty();
  ::memset(&_impl_.id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.status_) -
      reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.status_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Claim::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Claim& this_ = static_cast<const Claim&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Claim::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Claim& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:debate.Claim)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 id = 1;
          if (this_._internal_id() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_id(), target);
          }

          // string sentence = 2;
          if (!this_._internal_sentence().empty()) {
            const std::string& _s = this_._internal_sentence();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "debate.Claim.sentence");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // string description = 3;
          if (!this_._internal_description().empty()) {
            const std::string& _s = this_._internal_description();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "debate.Claim.description");
            target = stream->WriteStringMaybeAliased(3, _s, target);
          }

          // int32 creator_id = 8;
          if (this_._internal_creator_id() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<8>(
                    stream, this_._internal_creator_id(), target);
          }

          // int32 debate_id = 9;
          if (this_._internal_debate_id() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<9>(
                    stream, this_._internal_debate_id(), target);
          }

          // repeated .debate.ClaimState history = 10;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_history_size());
               i < n; i++) {
            const auto& repfield = this_._internal_history().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    10, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          // .debate.ClaimStatus status = 11;
          if (this_._internal_status() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                11, this_._internal_status(), target);
          }

          // repeated int32 link_ids = 12;
          {
            int byte_size = this_._impl_._link_ids_cached_byte_size_.Get();
            if (byte_size > 0) {
              target = stream->WriteInt32Packed(
                  12, this_._internal_link_ids(), byte_size, target);
            }
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:debate.Claim)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Claim::ByteSizeLong(const MessageLite& base) {
          const Claim& this_ = static_cast<const Claim&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Claim::ByteSizeLong() const {
          const Claim& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:debate.Claim)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .debate.ClaimState history = 10;
            {
              total_size += 1UL * this_._internal_history_size();
              for (const auto& msg : this_._internal_history()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
            // repeated int32 link_ids = 12;
            {
              total_size +=
                  ::_pbi::WireFormatLite::Int32SizeWithPackedTagSize(
                      this_._internal_link_ids(), 1,
                      this_._impl_._link_ids_cached_byte_size_);
            }
          }
           {
            // string sentence = 2;
            if (!this_._internal_sentence().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_sentence());
            }
            // string description = 3;
            if (!this_._internal_description().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_description());
            }
            // int32 id = 1;
            if (this_._internal_id() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_id());
            }
            // int32 creator_id = 8;
            if (this_._internal_creator_id() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_creator_id());
            }
            // int32 debate_id = 9;
            if (this_._internal_debate_id() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_debate_id());
            }
            // .debate.ClaimStatus status = 11;
            if (this_._internal_status() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_status());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Claim::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Claim*>(&to_msg);
  auto& from = static_cast<const Claim&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:debate.Claim)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_history()->MergeFrom(
      from._internal_history());
  _this->_internal_mutable_link_ids()->MergeFrom(from._internal_link_ids());
  if (!from._internal_sentence().empty()) {
    _this->_internal_set_sentence(from._internal_sentence());
  }
  if (!from._internal_description().empty()) {
    _this->_internal_set_description(from._internal_description());
  }
  if (from._internal_id() != 0) {
    _this->_impl_.id_ = from._impl_.id_;
  }
  if (from._internal_creator_id() != 0) {
    _this->_impl_.creator_id_ = from._impl_.creator_id_;
  }
  if (from._internal_debate_id() != 0) {
    _this->_impl_.debate_id_ = from._impl_.debate_id_;
  }
  if (from._internal_status() != 0) {
    _this->_impl_.status_ = from._impl_.status_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Claim::CopyFrom(const Claim& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:debate.Claim)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Claim::InternalSwap(Claim* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.history_.InternalSwap(&other->_impl_.history_);
  _impl_.link_ids_.InternalSwap(&other->_impl_.link_ids_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.sentence_, &other->_impl_.sentence_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.description_, &other->_impl_.description_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Claim, _impl_.status_)
      + sizeof(Claim::_impl_.status_)
      - PROTOBUF_FIELD_OFFSET(Claim, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::google::protobuf::Metadata Claim::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ClaimState::_Internal {
 public:
  using HasBits =
      decltype(std::declval<ClaimState>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ClaimState, _impl_._has_bits_);
};

void ClaimState::clear_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.timestamp_ != nullptr) _impl_.timestamp_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
ClaimState::ClaimState(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:debate.ClaimState)
}
inline PROTOBUF_NDEBUG_INLINE ClaimState::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::debate::ClaimState& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

ClaimState::ClaimState(
    ::google::protobuf::Arena* arena,
    const ClaimState& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ClaimState* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.claim_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::debate::Claim>(
                              arena, *from._impl_.claim_)
                        : nullptr;
  _impl_.timestamp_ = (cached_has_bits & 0x00000002u) ? ::google::protobuf::Message::CopyConstruct<::google::protobuf::Timestamp>(
                              arena, *from._impl_.timestamp_)
                        : nullptr;

  // @@protoc_insertion_point(copy_constructor:debate.ClaimState)
}
inline PROTOBUF_NDEBUG_INLINE ClaimState::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ClaimState::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, claim_),
           0,
           offsetof(Impl_, timestamp_) -
               offsetof(Impl_, claim_) +
               sizeof(Impl_::timestamp_));
}
ClaimState::~ClaimState() {
  // @@protoc_insertion_point(destructor:debate.ClaimState)
  SharedDtor(*this);
}
inline void ClaimState::SharedDtor(MessageLite& self) {
  ClaimState& this_ = static_cast<ClaimState&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.claim_;
  delete this_._impl_.timestamp_;
  this_._impl_.~Impl_();
}

inline void* ClaimState::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ClaimState(arena);
}
constexpr auto ClaimState::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(ClaimState),
                                            alignof(ClaimState));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ClaimState::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ClaimState_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ClaimState::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ClaimState>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ClaimState::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ClaimState>(), &ClaimState::ByteSizeLong,
            &ClaimState::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ClaimState, _impl_._cached_size_),
        false,
    },
    &ClaimState::kDescriptorMethods,
    &descriptor_table_debate_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ClaimState::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 2, 0, 2> ClaimState::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ClaimState, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::debate::ClaimState>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .google.protobuf.Timestamp timestamp = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 1, 1, PROTOBUF_FIELD_OFFSET(ClaimState, _impl_.timestamp_)}},
    // .debate.Claim claim = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(ClaimState, _impl_.claim_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .debate.Claim claim = 1;
    {PROTOBUF_FIELD_OFFSET(ClaimState, _impl_.claim_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .google.protobuf.Timestamp timestamp = 2;
    {PROTOBUF_FIELD_OFFSET(ClaimState, _impl_.timestamp_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::debate::Claim>()},
    {::_pbi::TcParser::GetTable<::google::protobuf::Timestamp>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void ClaimState::Clear() {
// @@protoc_insertion_point(message_clear_start:debate.ClaimState)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.claim_ != nullptr);
      _impl_.claim_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.timestamp_ != nullptr);
      _impl_.timestamp_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ClaimState::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ClaimState& this_ = static_cast<const ClaimState&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ClaimState::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ClaimState& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:debate.ClaimState)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // .debate.Claim claim = 1;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                1, *this_._impl_.claim_, this_._impl_.claim_->GetCachedSize(), target,
                stream);
          }

          // .google.protobuf.Timestamp timestamp = 2;
          if (cached_has_bits & 0x00000002u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                2, *this_._impl_.timestamp_, this_._impl_.timestamp_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:debate.ClaimState)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ClaimState::ByteSizeLong(const MessageLite& base) {
          const ClaimState& this_ = static_cast<const ClaimState&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ClaimState::ByteSizeLong() const {
          const ClaimState& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:debate.ClaimState)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x00000003u) {
            // .debate.Claim claim = 1;
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.claim_);
            }
            // .google.protobuf.Timestamp timestamp = 2;
            if (cached_has_bits & 0x00000002u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.timestamp_);
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ClaimState::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ClaimState*>(&to_msg);
  auto& from = static_cast<const ClaimState&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:debate.ClaimState)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(from._impl_.claim_ != nullptr);
      if (_this->_impl_.claim_ == nullptr) {
        _this->_impl_.claim_ =
            ::google::protobuf::Message::CopyConstruct<::debate::Claim>(arena, *from._impl_.claim_);
      } else {
        _this->_impl_.claim_->MergeFrom(*from._impl_.claim_);
      }
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(from._impl_.timestamp_ != nullptr);
      if (_this->_impl_.timestamp_ == nullptr) {
        _this->_impl_.timestamp_ =
            ::google::protobuf::Message::CopyConstruct<::google::protobuf::Timestamp>(arena, *from._impl_.timestamp_);
      } else {
        _this->_impl_.timestamp_->MergeFrom(*from._impl_.timestamp_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ClaimState::CopyFrom(const ClaimState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:debate.ClaimState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ClaimState::InternalSwap(ClaimState* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ClaimState, _impl_.timestamp_)
      + sizeof(ClaimState::_impl_.timestamp_)
      - PROTOBUF_FIELD_OFFSET(ClaimState, _impl_.claim_)>(
          reinterpret_cast<char*>(&_impl_.claim_),
          reinterpret_cast<char*>(&other->_impl_.claim_));
}

::google::protobuf::Metadata ClaimState::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Link::_Internal {
 public:
};

Link::Link(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:debate.Link)
}
inline PROTOBUF_NDEBUG_INLINE Link::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::debate::Link& from_msg)
      : connection_(arena, from.connection_),
        _cached_size_{0} {}

Link::Link(
    ::google::protobuf::Arena* arena,
    const Link& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Link* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, id_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, id_),
           offsetof(Impl_, debate_id_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::debate_id_));

  // @@protoc_insertion_point(copy_constructor:debate.Link)
}
inline PROTOBUF_NDEBUG_INLINE Link::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : connection_(arena),
        _cached_size_{0} {}

inline void Link::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, id_),
           0,
           offsetof(Impl_, debate_id_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::debate_id_));
}
Link::~Link() {
  // @@protoc_insertion_point(destructor:debate.Link)
  SharedDtor(*this);
}
inline void Link::SharedDtor(MessageLite& self) {
  Link& this_ = static_cast<Link&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.connection_.Destroy();
  this_._impl_.~Impl_();
}

inline void* Link::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Link(arena);
}
constexpr auto Link::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Link),
                                            alignof(Link));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Link::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Link_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Link::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Link>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Link::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Link>(), &Link::ByteSizeLong,
            &Link::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Link, _impl_._cached_size_),
        false,
    },
    &Link::kDescriptorMethods,
    &descriptor_table_debate_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Link::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 7, 0, 30, 2> Link::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    7, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967168,  // skipmap
    offsetof(decltype(_table_), field_entries),
    7,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::debate::Link>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Link, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(Link, _impl_.id_)}},
    // int32 connect_from = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Link, _impl_.connect_from_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(Link, _impl_.connect_from_)}},
    // int32 connect_to = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Link, _impl_.connect_to_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(Link, _impl_.connect_to_)}},
    // string connection = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(Link, _impl_.connection_)}},
    // int32 creator_id = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Link, _impl_.creator_id_), 63>(),
     {40, 63, 0, PROTOBUF_FIELD_OFFSET(Link, _impl_.creator_id_)}},
    // .debate.LinkType link_type = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Link, _impl_.link_type_), 63>(),
     {48, 63, 0, PROTOBUF_FIELD_OFFSET(Link, _impl_.link_type_)}},
    // int32 debate_id = 7;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Link, _impl_.debate_id_), 63>(),
     {56, 63, 0, PROTOBUF_FIELD_OFFSET(Link, _impl_.debate_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 id = 1;
    {PROTOBUF_FIELD_OFFSET(Link, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 connect_from = 2;
    {PROTOBUF_FIELD_OFFSET(Link, _impl_.connect_from_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 connect_to = 3;
    {PROTOBUF_FIELD_OFFSET(Link, _impl_.connect_to_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string connection = 4;
    {PROTOBUF_FIELD_OFFSET(Link, _impl_.connection_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 creator_id = 5;
    {PROTOBUF_FIELD_OFFSET(Link, _impl_.creator_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // .debate.LinkType link_type = 6;
    {PROTOBUF_FIELD_OFFSET(Link, _impl_.link_type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // int32 debate_id = 7;
    {PROTOBUF_FIELD_OFFSET(Link, _impl_.debate_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\13\0\0\0\12\0\0\0"
    "debate.Link"
    "connection"
  }},
};

PROTOBUF_NOINLINE void Link::Clear() {
// @@protoc_insertion_point(message_clear_start:debate.Link)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.connection_.ClearToEmpty();
  ::memset(&_impl_.id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.debate_id_) -
      reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.debate_id_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Link::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Link& this_ = static_cast<const Link&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Link::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Link& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:debate.Link)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 id = 1;
          if (this_._internal_id() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_id(), target);
          }

          // int32 connect_from = 2;
          if (this_._internal_connect_from() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_connect_from(), target);
          }

          // int32 connect_to = 3;
          if (this_._internal_connect_to() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<3>(
                    stream, this_._internal_connect_to(), target);
          }

          // string connection = 4;
          if (!this_._internal_connection().empty()) {
            const std::string& _s = this_._internal_connection();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "debate.Link.connection");
            target = stream->WriteStringMaybeAliased(4, _s, target);
          }

          // int32 creator_id = 5;
          if (this_._internal_creator_id() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<5>(
                    stream, this_._internal_creator_id(), target);
          }

          // .debate.LinkType link_type = 6;
          if (this_._internal_link_type() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                6, this_._internal_link_type(), target);
          }

          // int32 debate_id = 7;
          if (this_._internal_debate_id() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<7>(
                    stream, this_._internal_debate_id(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:debate.Link)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Link::ByteSizeLong(const MessageLite& base) {
          const Link& this_ = static_cast<const Link&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Link::ByteSizeLong() const {
          const Link& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:debate.Link)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string connection = 4;
            if (!this_._internal_connection().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_connection());
            }
            // int32 id = 1;
            if (this_._internal_id() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_id());
            }
            // int32 connect_from = 2;
            if (this_._internal_connect_from() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_connect_from());
            }
            // int32 connect_to = 3;
            if (this_._internal_connect_to() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_connect_to());
            }
            // int32 creator_id = 5;
            if (this_._internal_creator_id() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_creator_id());
            }
            // .debate.LinkType link_type = 6;
            if (this_._internal_link_type() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_link_type());
            }
            // int32 debate_id = 7;
            if (this_._internal_debate_id() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_debate_id());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Link::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Link*>(&to_msg);
  auto& from = static_cast<const Link&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:debate.Link)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_connection().empty()) {
    _this->_internal_set_connection(from._internal_connection());
  }
  if (from._internal_id() != 0) {
    _this->_impl_.id_ = from._impl_.id_;
  }
  if (from._internal_connect_from() != 0) {
    _this->_impl_.connect_from_ = from._impl_.connect_from_;
  }
  if (from._internal_connect_to() != 0) {
    _this->_impl_.connect_to_ = from._impl_.connect_to_;
  }
  if (from._internal_creator_id() != 0) {
    _this->_impl_.creator_id_ = from._impl_.creator_id_;
  }
  if (from._internal_link_type() != 0) {
    _this->_impl_.link_type_ = from._impl_.link_type_;
  }
  if (from._internal_debate_id() != 0) {
    _this->_impl_.debate_id_ = from._impl_.debate_id_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Link::CopyFrom(const Link& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:debate.Link)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Link::InternalSwap(Link* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.connection_, &other->_impl_.connection_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Link, _impl_.debate_id_)
      + sizeof(Link::_impl_.debate_id_)
      - PROTOBUF_FIELD_OFFSET(Link, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::google::protobuf::Metadata Link::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Debate::_Internal {
 public:
  using HasBits =
      decltype(std::declval<Debate>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Debate, _impl_._has_bits_);
};

void Debate::clear_settings() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.settings_ != nullptr) _impl_.settings_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
Debate::Debate(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:debate.Debate)
}
inline PROTOBUF_NDEBUG_INLINE Debate::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::debate::Debate& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        debater_ids_{visibility, arena, from.debater_ids_},
        _debater_ids_cached_byte_size_{0},
        topic_(arena, from.topic_) {}

Debate::Debate(
    ::google::protobuf::Arena* arena,
    const Debate& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Debate* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.settings_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::debate::DebateSettings>(
                              arena, *from._impl_.settings_)
                        : nullptr;
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, id_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, id_),
           offsetof(Impl_, parent_challenge_id_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::parent_challenge_id_));

  // @@protoc_insertion_point(copy_constructor:debate.Debate)
}
inline PROTOBUF_NDEBUG_INLINE Debate::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        debater_ids_{visibility, arena},
        _debater_ids_cached_byte_size_{0},
        topic_(arena) {}

inline void Debate::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, settings_),
           0,
           offsetof(Impl_, parent_challenge_id_) -
               offsetof(Impl_, settings_) +
               sizeof(Impl_::parent_challenge_id_));
}
Debate::~Debate() {
  // @@protoc_insertion_point(destructor:debate.Debate)
  SharedDtor(*this);
}
inline void Debate::SharedDtor(MessageLite& self) {
  Debate& this_ = static_cast<Debate&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.topic_.Destroy();
  delete this_._impl_.settings_;
  this_._impl_.~Impl_();
}

inline void* Debate::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Debate(arena);
}
constexpr auto Debate::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(Debate, _impl_.debater_ids_) +
          decltype(Debate::_impl_.debater_ids_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(Debate), alignof(Debate), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&Debate::PlacementNew_,
                                 sizeof(Debate),
                                 alignof(Debate));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Debate::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Debate_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Debate::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Debate>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Debate::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Debate>(), &Debate::ByteSizeLong,
            &Debate::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Debate, _impl_._cached_size_),
        false,
    },
    &Debate::kDescriptorMethods,
    &descriptor_table_debate_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Debate::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 8, 1, 35, 2> Debate::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Debate, _impl_._has_bits_),
    0, // no _extensions_
    8, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967040,  // skipmap
    offsetof(decltype(_table_), field_entries),
    8,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::debate::Debate>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 parent_challenge_id = 8;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Debate, _impl_.parent_challenge_id_), 63>(),
     {64, 63, 0, PROTOBUF_FIELD_OFFSET(Debate, _impl_.parent_challenge_id_)}},
    // int32 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Debate, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(Debate, _impl_.id_)}},
    // int32 root_claim_id = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Debate, _impl_.root_claim_id_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(Debate, _impl_.root_claim_id_)}},
    // string topic = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(Debate, _impl_.topic_)}},
    // repeated int32 debater_ids = 4;
    {::_pbi::TcParser::FastV32P1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(Debate, _impl_.debater_ids_)}},
    // int32 creator_id = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Debate, _impl_.creator_id_), 63>(),
     {40, 63, 0, PROTOBUF_FIELD_OFFSET(Debate, _impl_.creator_id_)}},
    // .debate.DebateSettings settings = 6;
    {::_pbi::TcParser::FastMtS1,
     {50, 0, 0, PROTOBUF_FIELD_OFFSET(Debate, _impl_.settings_)}},
    // bool is_challenge = 7;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(Debate, _impl_.is_challenge_), 63>(),
     {56, 63, 0, PROTOBUF_FIELD_OFFSET(Debate, _impl_.is_challenge_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 id = 1;
    {PROTOBUF_FIELD_OFFSET(Debate, _impl_.id_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 root_claim_id = 2;
    {PROTOBUF_FIELD_OFFSET(Debate, _impl_.root_claim_id_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string topic = 3;
    {PROTOBUF_FIELD_OFFSET(Debate, _impl_.topic_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // repeated int32 debater_ids = 4;
    {PROTOBUF_FIELD_OFFSET(Debate, _impl_.debater_ids_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedInt32)},
    // int32 creator_id = 5;
    {PROTOBUF_FIELD_OFFSET(Debate, _impl_.creator_id_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // .debate.DebateSettings settings = 6;
    {PROTOBUF_FIELD_OFFSET(Debate, _impl_.settings_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // bool is_challenge = 7;
    {PROTOBUF_FIELD_OFFSET(Debate, _impl_.is_challenge_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // int32 parent_challenge_id = 8;
    {PROTOBUF_FIELD_OFFSET(Debate, _impl_.parent_challenge_id_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }}, {{
    {::_pbi::TcParser::GetTable<::debate::DebateSettings>()},
  }}, {{
    "\15\0\0\5\0\0\0\0\0\0\0\0\0\0\0\0"
    "debate.Debate"
    "topic"
  }},
};

PROTOBUF_NOINLINE void Debate::Clear() {
// @@protoc_insertion_point(message_clear_start:debate.Debate)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.debater_ids_.Clear();
  _impl_.topic_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.settings_ != nullptr);
    _impl_.settings_->Clear();
  }
  ::memset(&_impl_.id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.parent_challenge_id_) -
      reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.parent_challenge_id_));
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Debate::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Debate& this_ = static_cast<const Debate&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Debate::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Debate& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:debate.Debate)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 id = 1;
          if (this_._internal_id() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_id(), target);
          }

          // int32 root_claim_id = 2;
          if (this_._internal_root_claim_id() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_root_claim_id(), target);
          }

          // string topic = 3;
          if (!this_._internal_topic().empty()) {
            const std::string& _s = this_._internal_topic();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "debate.Debate.topic");
            target = stream->WriteStringMaybeAliased(3, _s, target);
          }

          // repeated int32 debater_ids = 4;
          {
            int byte_size = this_._impl_._debater_ids_cached_byte_size_.Get();
            if (byte_size > 0) {
              target = stream->WriteInt32Packed(
                  4, this_._internal_debater_ids(), byte_size, target);
            }
          }

          // int32 creator_id = 5;
          if (this_._internal_creator_id() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<5>(
                    stream, this_._internal_creator_id(), target);
          }

          cached_has_bits = this_._impl_._has_bits_[0];
          // .debate.DebateSettings settings = 6;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                6, *this_._impl_.settings_, this_._impl_.settings_->GetCachedSize(), target,
                stream);
          }

          // bool is_challenge = 7;
          if (this_._internal_is_challenge() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                7, this_._internal_is_challenge(), target);
          }

          // int32 parent_challenge_id = 8;
          if (this_._internal_parent_challenge_id() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<8>(
                    stream, this_._internal_parent_challenge_id(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:debate.Debate)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Debate::ByteSizeLong(const MessageLite& base) {
          const Debate& this_ = static_cast<const Debate&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Debate::ByteSizeLong() const {
          const Debate& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:debate.Debate)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated int32 debater_ids = 4;
            {
              total_size +=
                  ::_pbi::WireFormatLite::Int32SizeWithPackedTagSize(
                      this_._internal_debater_ids(), 1,
                      this_._impl_._debater_ids_cached_byte_size_);
            }
          }
           {
            // string topic = 3;
            if (!this_._internal_topic().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_topic());
            }
          }
           {
            // .debate.DebateSettings settings = 6;
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.settings_);
            }
          }
           {
            // int32 id = 1;
            if (this_._internal_id() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_id());
            }
            // int32 root_claim_id = 2;
            if (this_._internal_root_claim_id() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_root_claim_id());
            }
            // int32 creator_id = 5;
            if (this_._internal_creator_id() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_creator_id());
            }
            // bool is_challenge = 7;
            if (this_._internal_is_challenge() != 0) {
              total_size += 2;
            }
            // int32 parent_challenge_id = 8;
            if (this_._internal_parent_challenge_id() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_parent_challenge_id());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Debate::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Debate*>(&to_msg);
  auto& from = static_cast<const Debate&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:debate.Debate)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_debater_ids()->MergeFrom(from._internal_debater_ids());
  if (!from._internal_topic().empty()) {
    _this->_internal_set_topic(from._internal_topic());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.settings_ != nullptr);
    if (_this->_impl_.settings_ == nullptr) {
      _this->_impl_.settings_ =
          ::google::protobuf::Message::CopyConstruct<::debate::DebateSettings>(arena, *from._impl_.settings_);
    } else {
      _this->_impl_.settings_->MergeFrom(*from._impl_.settings_);
    }
  }
  if (from._internal_id() != 0) {
    _this->_impl_.id_ = from._impl_.id_;
  }
  if (from._internal_root_claim_id() != 0) {
    _this->_impl_.root_claim_id_ = from._impl_.root_claim_id_;
  }
  if (from._internal_creator_id() != 0) {
    _this->_impl_.creator_id_ = from._impl_.creator_id_;
  }
  if (from._internal_is_challenge() != 0) {
    _this->_impl_.is_challenge_ = from._impl_.is_challenge_;
  }
  if (from._internal_parent_challenge_id() != 0) {
    _this->_impl_.parent_challenge_id_ = from._impl_.parent_challenge_id_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Debate::CopyFrom(const Debate& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:debate.Debate)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Debate::InternalSwap(Debate* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.debater_ids_.InternalSwap(&other->_impl_.debater_ids_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.topic_, &other->_impl_.topic_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Debate, _impl_.parent_challenge_id_)
      + sizeof(Debate::_impl_.parent_challenge_id_)
      - PROTOBUF_FIELD_OFFSET(Debate, _impl_.settings_)>(
          reinterpret_cast<char*>(&_impl_.settings_),
          reinterpret_cast<char*>(&other->_impl_.settings_));
}

::google::protobuf::Metadata Debate::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace debate
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_debate_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
