// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: scope.proto
// Protobuf C++ Version: 5.29.5

#include "scope.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace debate {

inline constexpr SingleClaimScope::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : debate_id_{0},
        current_claim_id_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SingleClaimScope::SingleClaimScope(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SingleClaimScopeDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SingleClaimScopeDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SingleClaimScopeDefaultTypeInternal() {}
  union {
    SingleClaimScope _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SingleClaimScopeDefaultTypeInternal _SingleClaimScope_default_instance_;

inline constexpr FullDebateScope::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : debate_id_{0},
        top_view_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR FullDebateScope::FullDebateScope(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct FullDebateScopeDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FullDebateScopeDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FullDebateScopeDefaultTypeInternal() {}
  union {
    FullDebateScope _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FullDebateScopeDefaultTypeInternal _FullDebateScope_default_instance_;

inline constexpr Scope::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : scopetype_{static_cast< ::debate::ScopeType >(0)},
        scope_info_{},
        _cached_size_{0},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR Scope::Scope(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ScopeDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ScopeDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ScopeDefaultTypeInternal() {}
  union {
    Scope _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ScopeDefaultTypeInternal _Scope_default_instance_;
}  // namespace debate
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_scope_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_scope_2eproto = nullptr;
const ::uint32_t
    TableStruct_scope_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::debate::SingleClaimScope, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::debate::SingleClaimScope, _impl_.debate_id_),
        PROTOBUF_FIELD_OFFSET(::debate::SingleClaimScope, _impl_.current_claim_id_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::debate::FullDebateScope, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::debate::FullDebateScope, _impl_.debate_id_),
        PROTOBUF_FIELD_OFFSET(::debate::FullDebateScope, _impl_.top_view_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::debate::Scope, _internal_metadata_),
        ~0u,  // no _extensions_
        PROTOBUF_FIELD_OFFSET(::debate::Scope, _impl_._oneof_case_[0]),
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::debate::Scope, _impl_.scopetype_),
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        PROTOBUF_FIELD_OFFSET(::debate::Scope, _impl_.scope_info_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::debate::SingleClaimScope)},
        {10, -1, -1, sizeof(::debate::FullDebateScope)},
        {20, -1, -1, sizeof(::debate::Scope)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::debate::_SingleClaimScope_default_instance_._instance,
    &::debate::_FullDebateScope_default_instance_._instance,
    &::debate::_Scope_default_instance_._instance,
};
const char descriptor_table_protodef_scope_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\013scope.proto\022\006debate\"\?\n\020SingleClaimScop"
    "e\022\021\n\tdebate_id\030\001 \001(\005\022\030\n\020current_claim_id"
    "\030\002 \001(\005\"6\n\017FullDebateScope\022\021\n\tdebate_id\030\001"
    " \001(\005\022\020\n\010top_view\030\002 \001(\010\"\235\001\n\005Scope\022$\n\tscop"
    "etype\030\001 \001(\0162\021.debate.ScopeType\0220\n\014single"
    "_claim\030\002 \001(\0132\030.debate.SingleClaimScopeH\000"
    "\022.\n\013full_debate\030\003 \001(\0132\027.debate.FullDebat"
    "eScopeH\000B\014\n\nscope_info*.\n\tScopeType\022\020\n\014S"
    "INGLE_CLAIM\020\000\022\017\n\013FULL_DEBATE\020\001b\006proto3"
};
static ::absl::once_flag descriptor_table_scope_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_scope_2eproto = {
    false,
    false,
    358,
    descriptor_table_protodef_scope_2eproto,
    "scope.proto",
    &descriptor_table_scope_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_scope_2eproto::offsets,
    file_level_enum_descriptors_scope_2eproto,
    file_level_service_descriptors_scope_2eproto,
};
namespace debate {
const ::google::protobuf::EnumDescriptor* ScopeType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_scope_2eproto);
  return file_level_enum_descriptors_scope_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t ScopeType_internal_data_[] = {
    131072u, 0u, };
bool ScopeType_IsValid(int value) {
  return 0 <= value && value <= 1;
}
// ===================================================================

class SingleClaimScope::_Internal {
 public:
};

SingleClaimScope::SingleClaimScope(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:debate.SingleClaimScope)
}
SingleClaimScope::SingleClaimScope(
    ::google::protobuf::Arena* arena, const SingleClaimScope& from)
    : SingleClaimScope(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE SingleClaimScope::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void SingleClaimScope::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, debate_id_),
           0,
           offsetof(Impl_, current_claim_id_) -
               offsetof(Impl_, debate_id_) +
               sizeof(Impl_::current_claim_id_));
}
SingleClaimScope::~SingleClaimScope() {
  // @@protoc_insertion_point(destructor:debate.SingleClaimScope)
  SharedDtor(*this);
}
inline void SingleClaimScope::SharedDtor(MessageLite& self) {
  SingleClaimScope& this_ = static_cast<SingleClaimScope&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* SingleClaimScope::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) SingleClaimScope(arena);
}
constexpr auto SingleClaimScope::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(SingleClaimScope),
                                            alignof(SingleClaimScope));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull SingleClaimScope::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_SingleClaimScope_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &SingleClaimScope::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<SingleClaimScope>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &SingleClaimScope::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<SingleClaimScope>(), &SingleClaimScope::ByteSizeLong,
            &SingleClaimScope::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(SingleClaimScope, _impl_._cached_size_),
        false,
    },
    &SingleClaimScope::kDescriptorMethods,
    &descriptor_table_scope_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* SingleClaimScope::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> SingleClaimScope::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::debate::SingleClaimScope>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 current_claim_id = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SingleClaimScope, _impl_.current_claim_id_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(SingleClaimScope, _impl_.current_claim_id_)}},
    // int32 debate_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SingleClaimScope, _impl_.debate_id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(SingleClaimScope, _impl_.debate_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 debate_id = 1;
    {PROTOBUF_FIELD_OFFSET(SingleClaimScope, _impl_.debate_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 current_claim_id = 2;
    {PROTOBUF_FIELD_OFFSET(SingleClaimScope, _impl_.current_claim_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void SingleClaimScope::Clear() {
// @@protoc_insertion_point(message_clear_start:debate.SingleClaimScope)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.debate_id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.current_claim_id_) -
      reinterpret_cast<char*>(&_impl_.debate_id_)) + sizeof(_impl_.current_claim_id_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* SingleClaimScope::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const SingleClaimScope& this_ = static_cast<const SingleClaimScope&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* SingleClaimScope::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const SingleClaimScope& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:debate.SingleClaimScope)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 debate_id = 1;
          if (this_._internal_debate_id() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_debate_id(), target);
          }

          // int32 current_claim_id = 2;
          if (this_._internal_current_claim_id() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_current_claim_id(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:debate.SingleClaimScope)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t SingleClaimScope::ByteSizeLong(const MessageLite& base) {
          const SingleClaimScope& this_ = static_cast<const SingleClaimScope&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t SingleClaimScope::ByteSizeLong() const {
          const SingleClaimScope& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:debate.SingleClaimScope)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // int32 debate_id = 1;
            if (this_._internal_debate_id() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_debate_id());
            }
            // int32 current_claim_id = 2;
            if (this_._internal_current_claim_id() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_current_claim_id());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void SingleClaimScope::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SingleClaimScope*>(&to_msg);
  auto& from = static_cast<const SingleClaimScope&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:debate.SingleClaimScope)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_debate_id() != 0) {
    _this->_impl_.debate_id_ = from._impl_.debate_id_;
  }
  if (from._internal_current_claim_id() != 0) {
    _this->_impl_.current_claim_id_ = from._impl_.current_claim_id_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SingleClaimScope::CopyFrom(const SingleClaimScope& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:debate.SingleClaimScope)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SingleClaimScope::InternalSwap(SingleClaimScope* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SingleClaimScope, _impl_.current_claim_id_)
      + sizeof(SingleClaimScope::_impl_.current_claim_id_)
      - PROTOBUF_FIELD_OFFSET(SingleClaimScope, _impl_.debate_id_)>(
          reinterpret_cast<char*>(&_impl_.debate_id_),
          reinterpret_cast<char*>(&other->_impl_.debate_id_));
}

::google::protobuf::Metadata SingleClaimScope::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class FullDebateScope::_Internal {
 public:
};

FullDebateScope::FullDebateScope(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:debate.FullDebateScope)
}
FullDebateScope::FullDebateScope(
    ::google::protobuf::Arena* arena, const FullDebateScope& from)
    : FullDebateScope(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE FullDebateScope::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void FullDebateScope::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, debate_id_),
           0,
           offsetof(Impl_, top_view_) -
               offsetof(Impl_, debate_id_) +
               sizeof(Impl_::top_view_));
}
FullDebateScope::~FullDebateScope() {
  // @@protoc_insertion_point(destructor:debate.FullDebateScope)
  SharedDtor(*this);
}
inline void FullDebateScope::SharedDtor(MessageLite& self) {
  FullDebateScope& this_ = static_cast<FullDebateScope&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* FullDebateScope::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) FullDebateScope(arena);
}
constexpr auto FullDebateScope::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(FullDebateScope),
                                            alignof(FullDebateScope));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull FullDebateScope::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_FullDebateScope_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &FullDebateScope::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<FullDebateScope>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &FullDebateScope::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<FullDebateScope>(), &FullDebateScope::ByteSizeLong,
            &FullDebateScope::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(FullDebateScope, _impl_._cached_size_),
        false,
    },
    &FullDebateScope::kDescriptorMethods,
    &descriptor_table_scope_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* FullDebateScope::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> FullDebateScope::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::debate::FullDebateScope>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool top_view = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(FullDebateScope, _impl_.top_view_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(FullDebateScope, _impl_.top_view_)}},
    // int32 debate_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(FullDebateScope, _impl_.debate_id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(FullDebateScope, _impl_.debate_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 debate_id = 1;
    {PROTOBUF_FIELD_OFFSET(FullDebateScope, _impl_.debate_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // bool top_view = 2;
    {PROTOBUF_FIELD_OFFSET(FullDebateScope, _impl_.top_view_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void FullDebateScope::Clear() {
// @@protoc_insertion_point(message_clear_start:debate.FullDebateScope)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.debate_id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.top_view_) -
      reinterpret_cast<char*>(&_impl_.debate_id_)) + sizeof(_impl_.top_view_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* FullDebateScope::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const FullDebateScope& this_ = static_cast<const FullDebateScope&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* FullDebateScope::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const FullDebateScope& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:debate.FullDebateScope)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 debate_id = 1;
          if (this_._internal_debate_id() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_debate_id(), target);
          }

          // bool top_view = 2;
          if (this_._internal_top_view() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                2, this_._internal_top_view(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:debate.FullDebateScope)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t FullDebateScope::ByteSizeLong(const MessageLite& base) {
          const FullDebateScope& this_ = static_cast<const FullDebateScope&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t FullDebateScope::ByteSizeLong() const {
          const FullDebateScope& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:debate.FullDebateScope)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // int32 debate_id = 1;
            if (this_._internal_debate_id() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_debate_id());
            }
            // bool top_view = 2;
            if (this_._internal_top_view() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void FullDebateScope::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<FullDebateScope*>(&to_msg);
  auto& from = static_cast<const FullDebateScope&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:debate.FullDebateScope)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_debate_id() != 0) {
    _this->_impl_.debate_id_ = from._impl_.debate_id_;
  }
  if (from._internal_top_view() != 0) {
    _this->_impl_.top_view_ = from._impl_.top_view_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void FullDebateScope::CopyFrom(const FullDebateScope& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:debate.FullDebateScope)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void FullDebateScope::InternalSwap(FullDebateScope* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(FullDebateScope, _impl_.top_view_)
      + sizeof(FullDebateScope::_impl_.top_view_)
      - PROTOBUF_FIELD_OFFSET(FullDebateScope, _impl_.debate_id_)>(
          reinterpret_cast<char*>(&_impl_.debate_id_),
          reinterpret_cast<char*>(&other->_impl_.debate_id_));
}

::google::protobuf::Metadata FullDebateScope::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Scope::_Internal {
 public:
  static constexpr ::int32_t kOneofCaseOffset =
      PROTOBUF_FIELD_OFFSET(::debate::Scope, _impl_._oneof_case_);
};

void Scope::set_allocated_single_claim(::debate::SingleClaimScope* single_claim) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_scope_info();
  if (single_claim) {
    ::google::protobuf::Arena* submessage_arena = single_claim->GetArena();
    if (message_arena != submessage_arena) {
      single_claim = ::google::protobuf::internal::GetOwnedMessage(message_arena, single_claim, submessage_arena);
    }
    set_has_single_claim();
    _impl_.scope_info_.single_claim_ = single_claim;
  }
  // @@protoc_insertion_point(field_set_allocated:debate.Scope.single_claim)
}
void Scope::set_allocated_full_debate(::debate::FullDebateScope* full_debate) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_scope_info();
  if (full_debate) {
    ::google::protobuf::Arena* submessage_arena = full_debate->GetArena();
    if (message_arena != submessage_arena) {
      full_debate = ::google::protobuf::internal::GetOwnedMessage(message_arena, full_debate, submessage_arena);
    }
    set_has_full_debate();
    _impl_.scope_info_.full_debate_ = full_debate;
  }
  // @@protoc_insertion_point(field_set_allocated:debate.Scope.full_debate)
}
Scope::Scope(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:debate.Scope)
}
inline PROTOBUF_NDEBUG_INLINE Scope::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::debate::Scope& from_msg)
      : scope_info_{},
        _cached_size_{0},
        _oneof_case_{from._oneof_case_[0]} {}

Scope::Scope(
    ::google::protobuf::Arena* arena,
    const Scope& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Scope* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.scopetype_ = from._impl_.scopetype_;
  switch (scope_info_case()) {
    case SCOPE_INFO_NOT_SET:
      break;
      case kSingleClaim:
        _impl_.scope_info_.single_claim_ = ::google::protobuf::Message::CopyConstruct<::debate::SingleClaimScope>(arena, *from._impl_.scope_info_.single_claim_);
        break;
      case kFullDebate:
        _impl_.scope_info_.full_debate_ = ::google::protobuf::Message::CopyConstruct<::debate::FullDebateScope>(arena, *from._impl_.scope_info_.full_debate_);
        break;
  }

  // @@protoc_insertion_point(copy_constructor:debate.Scope)
}
inline PROTOBUF_NDEBUG_INLINE Scope::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : scope_info_{},
        _cached_size_{0},
        _oneof_case_{} {}

inline void Scope::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.scopetype_ = {};
}
Scope::~Scope() {
  // @@protoc_insertion_point(destructor:debate.Scope)
  SharedDtor(*this);
}
inline void Scope::SharedDtor(MessageLite& self) {
  Scope& this_ = static_cast<Scope&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  if (this_.has_scope_info()) {
    this_.clear_scope_info();
  }
  this_._impl_.~Impl_();
}

void Scope::clear_scope_info() {
// @@protoc_insertion_point(one_of_clear_start:debate.Scope)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (scope_info_case()) {
    case kSingleClaim: {
      if (GetArena() == nullptr) {
        delete _impl_.scope_info_.single_claim_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.scope_info_.single_claim_);
      }
      break;
    }
    case kFullDebate: {
      if (GetArena() == nullptr) {
        delete _impl_.scope_info_.full_debate_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.scope_info_.full_debate_);
      }
      break;
    }
    case SCOPE_INFO_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = SCOPE_INFO_NOT_SET;
}


inline void* Scope::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Scope(arena);
}
constexpr auto Scope::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Scope),
                                            alignof(Scope));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Scope::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Scope_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Scope::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Scope>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Scope::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Scope>(), &Scope::ByteSizeLong,
            &Scope::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Scope, _impl_._cached_size_),
        false,
    },
    &Scope::kDescriptorMethods,
    &descriptor_table_scope_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Scope::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 3, 2, 0, 2> Scope::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::debate::Scope>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .debate.ScopeType scopetype = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Scope, _impl_.scopetype_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(Scope, _impl_.scopetype_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .debate.ScopeType scopetype = 1;
    {PROTOBUF_FIELD_OFFSET(Scope, _impl_.scopetype_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // .debate.SingleClaimScope single_claim = 2;
    {PROTOBUF_FIELD_OFFSET(Scope, _impl_.scope_info_.single_claim_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .debate.FullDebateScope full_debate = 3;
    {PROTOBUF_FIELD_OFFSET(Scope, _impl_.scope_info_.full_debate_), _Internal::kOneofCaseOffset + 0, 1,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::debate::SingleClaimScope>()},
    {::_pbi::TcParser::GetTable<::debate::FullDebateScope>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void Scope::Clear() {
// @@protoc_insertion_point(message_clear_start:debate.Scope)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.scopetype_ = 0;
  clear_scope_info();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Scope::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Scope& this_ = static_cast<const Scope&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Scope::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Scope& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:debate.Scope)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // .debate.ScopeType scopetype = 1;
          if (this_._internal_scopetype() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                1, this_._internal_scopetype(), target);
          }

          switch (this_.scope_info_case()) {
            case kSingleClaim: {
              target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                  2, *this_._impl_.scope_info_.single_claim_, this_._impl_.scope_info_.single_claim_->GetCachedSize(), target,
                  stream);
              break;
            }
            case kFullDebate: {
              target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                  3, *this_._impl_.scope_info_.full_debate_, this_._impl_.scope_info_.full_debate_->GetCachedSize(), target,
                  stream);
              break;
            }
            default:
              break;
          }
          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:debate.Scope)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Scope::ByteSizeLong(const MessageLite& base) {
          const Scope& this_ = static_cast<const Scope&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Scope::ByteSizeLong() const {
          const Scope& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:debate.Scope)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // .debate.ScopeType scopetype = 1;
            if (this_._internal_scopetype() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_scopetype());
            }
          }
          switch (this_.scope_info_case()) {
            // .debate.SingleClaimScope single_claim = 2;
            case kSingleClaim: {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.scope_info_.single_claim_);
              break;
            }
            // .debate.FullDebateScope full_debate = 3;
            case kFullDebate: {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.scope_info_.full_debate_);
              break;
            }
            case SCOPE_INFO_NOT_SET: {
              break;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Scope::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Scope*>(&to_msg);
  auto& from = static_cast<const Scope&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:debate.Scope)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_scopetype() != 0) {
    _this->_impl_.scopetype_ = from._impl_.scopetype_;
  }
  if (const uint32_t oneof_from_case = from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_scope_info();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kSingleClaim: {
        if (oneof_needs_init) {
          _this->_impl_.scope_info_.single_claim_ =
              ::google::protobuf::Message::CopyConstruct<::debate::SingleClaimScope>(arena, *from._impl_.scope_info_.single_claim_);
        } else {
          _this->_impl_.scope_info_.single_claim_->MergeFrom(from._internal_single_claim());
        }
        break;
      }
      case kFullDebate: {
        if (oneof_needs_init) {
          _this->_impl_.scope_info_.full_debate_ =
              ::google::protobuf::Message::CopyConstruct<::debate::FullDebateScope>(arena, *from._impl_.scope_info_.full_debate_);
        } else {
          _this->_impl_.scope_info_.full_debate_->MergeFrom(from._internal_full_debate());
        }
        break;
      }
      case SCOPE_INFO_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Scope::CopyFrom(const Scope& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:debate.Scope)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Scope::InternalSwap(Scope* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.scopetype_, other->_impl_.scopetype_);
  swap(_impl_.scope_info_, other->_impl_.scope_info_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata Scope::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace debate
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_scope_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
