// source: page.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.ui.Component');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Map');
goog.require('jspb.Message');
goog.require('proto.ui.ListItem');
goog.require('proto.ui.Style');

goog.forwardDeclare('proto.ui.ComponentType');
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ui.Component = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.ui.Component.repeatedFields_, null);
};
goog.inherits(proto.ui.Component, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ui.Component.displayName = 'proto.ui.Component';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.ui.Component.repeatedFields_ = [4,11];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ui.Component.prototype.toObject = function(opt_includeInstance) {
  return proto.ui.Component.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ui.Component} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ui.Component.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    type: jspb.Message.getFieldWithDefault(msg, 2, 0),
    text: jspb.Message.getFieldWithDefault(msg, 3, ""),
    childrenList: jspb.Message.toObjectList(msg.getChildrenList(),
    proto.ui.Component.toObject, includeInstance),
    style: (f = msg.getStyle()) && proto.ui.Style.toObject(includeInstance, f),
    cssMap: (f = msg.getCssMap()) ? f.toObject(includeInstance, undefined) : [],
    eventsMap: (f = msg.getEventsMap()) ? f.toObject(includeInstance, undefined) : [],
    attributesMap: (f = msg.getAttributesMap()) ? f.toObject(includeInstance, undefined) : [],
    name: jspb.Message.getFieldWithDefault(msg, 9, ""),
    value: jspb.Message.getFieldWithDefault(msg, 10, ""),
    itemsList: jspb.Message.toObjectList(msg.getItemsList(),
    proto.ui.ListItem.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ui.Component}
 */
proto.ui.Component.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ui.Component;
  return proto.ui.Component.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ui.Component} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ui.Component}
 */
proto.ui.Component.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {!proto.ui.ComponentType} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setText(value);
      break;
    case 4:
      var value = new proto.ui.Component;
      reader.readMessage(value,proto.ui.Component.deserializeBinaryFromReader);
      msg.addChildren(value);
      break;
    case 5:
      var value = new proto.ui.Style;
      reader.readMessage(value,proto.ui.Style.deserializeBinaryFromReader);
      msg.setStyle(value);
      break;
    case 6:
      var value = msg.getCssMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    case 7:
      var value = msg.getEventsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    case 8:
      var value = msg.getAttributesMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setValue(value);
      break;
    case 11:
      var value = new proto.ui.ListItem;
      reader.readMessage(value,proto.ui.ListItem.deserializeBinaryFromReader);
      msg.addItems(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ui.Component.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ui.Component.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ui.Component} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ui.Component.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getText();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getChildrenList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.ui.Component.serializeBinaryToWriter
    );
  }
  f = message.getStyle();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.ui.Style.serializeBinaryToWriter
    );
  }
  f = message.getCssMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(6, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
  f = message.getEventsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(7, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
  f = message.getAttributesMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(8, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getValue();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getItemsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      11,
      f,
      proto.ui.ListItem.serializeBinaryToWriter
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.ui.Component.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.ui.Component} returns this
 */
proto.ui.Component.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional ComponentType type = 2;
 * @return {!proto.ui.ComponentType}
 */
proto.ui.Component.prototype.getType = function() {
  return /** @type {!proto.ui.ComponentType} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.ui.ComponentType} value
 * @return {!proto.ui.Component} returns this
 */
proto.ui.Component.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional string text = 3;
 * @return {string}
 */
proto.ui.Component.prototype.getText = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.ui.Component} returns this
 */
proto.ui.Component.prototype.setText = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * repeated Component children = 4;
 * @return {!Array<!proto.ui.Component>}
 */
proto.ui.Component.prototype.getChildrenList = function() {
  return /** @type{!Array<!proto.ui.Component>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.ui.Component, 4));
};


/**
 * @param {!Array<!proto.ui.Component>} value
 * @return {!proto.ui.Component} returns this
*/
proto.ui.Component.prototype.setChildrenList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.ui.Component=} opt_value
 * @param {number=} opt_index
 * @return {!proto.ui.Component}
 */
proto.ui.Component.prototype.addChildren = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.ui.Component, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.ui.Component} returns this
 */
proto.ui.Component.prototype.clearChildrenList = function() {
  return this.setChildrenList([]);
};


/**
 * optional Style style = 5;
 * @return {?proto.ui.Style}
 */
proto.ui.Component.prototype.getStyle = function() {
  return /** @type{?proto.ui.Style} */ (
    jspb.Message.getWrapperField(this, proto.ui.Style, 5));
};


/**
 * @param {?proto.ui.Style|undefined} value
 * @return {!proto.ui.Component} returns this
*/
proto.ui.Component.prototype.setStyle = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ui.Component} returns this
 */
proto.ui.Component.prototype.clearStyle = function() {
  return this.setStyle(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ui.Component.prototype.hasStyle = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * map<string, string> css = 6;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.ui.Component.prototype.getCssMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 6, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.ui.Component} returns this
 */
proto.ui.Component.prototype.clearCssMap = function() {
  this.getCssMap().clear();
  return this;};


/**
 * map<string, string> events = 7;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.ui.Component.prototype.getEventsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 7, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.ui.Component} returns this
 */
proto.ui.Component.prototype.clearEventsMap = function() {
  this.getEventsMap().clear();
  return this;};


/**
 * map<string, string> attributes = 8;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.ui.Component.prototype.getAttributesMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 8, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.ui.Component} returns this
 */
proto.ui.Component.prototype.clearAttributesMap = function() {
  this.getAttributesMap().clear();
  return this;};


/**
 * optional string name = 9;
 * @return {string}
 */
proto.ui.Component.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.ui.Component} returns this
 */
proto.ui.Component.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional string value = 10;
 * @return {string}
 */
proto.ui.Component.prototype.getValue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.ui.Component} returns this
 */
proto.ui.Component.prototype.setValue = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * repeated ListItem items = 11;
 * @return {!Array<!proto.ui.ListItem>}
 */
proto.ui.Component.prototype.getItemsList = function() {
  return /** @type{!Array<!proto.ui.ListItem>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.ui.ListItem, 11));
};


/**
 * @param {!Array<!proto.ui.ListItem>} value
 * @return {!proto.ui.Component} returns this
*/
proto.ui.Component.prototype.setItemsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 11, value);
};


/**
 * @param {!proto.ui.ListItem=} opt_value
 * @param {number=} opt_index
 * @return {!proto.ui.ListItem}
 */
proto.ui.Component.prototype.addItems = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 11, opt_value, proto.ui.ListItem, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.ui.Component} returns this
 */
proto.ui.Component.prototype.clearItemsList = function() {
  return this.setItemsList([]);
};


