// @generated by protoc-gen-es v2.6.3
// @generated from file hello.proto (syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file hello.proto.
 */
export const file_hello = /*@__PURE__*/
  fileDesc("CgtoZWxsby5wcm90byIcCgxIZWxsb1JlcXVlc3QSDAoEbmFtZRgBIAEoCSIdCgpIZWxsb1JlcGx5Eg8KB21lc3NhZ2UYASABKAkyMQoHR3JlZXRlchImCghTYXlIZWxsbxINLkhlbGxvUmVxdWVzdBoLLkhlbGxvUmVwbHliBnByb3RvMw");

/**
 * Describes the message HelloRequest.
 * Use `create(HelloRequestSchema)` to create a new message.
 */
export const HelloRequestSchema = /*@__PURE__*/
  messageDesc(file_hello, 0);

/**
 * Describes the message HelloReply.
 * Use `create(HelloReplySchema)` to create a new message.
 */
export const HelloReplySchema = /*@__PURE__*/
  messageDesc(file_hello, 1);

/**
 * @generated from service Greeter
 */
export const Greeter = /*@__PURE__*/
  serviceDesc(file_hello, 0);

