// source: page.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.ui.Style');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.ui.Position');
goog.require('proto.ui.Size');

goog.forwardDeclare('proto.ui.LayoutType');
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ui.Style = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ui.Style, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ui.Style.displayName = 'proto.ui.Style';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ui.Style.prototype.toObject = function(opt_includeInstance) {
  return proto.ui.Style.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ui.Style} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ui.Style.toObject = function(includeInstance, msg) {
  var f, obj = {
    layout: jspb.Message.getFieldWithDefault(msg, 1, 0),
    position: (f = msg.getPosition()) && proto.ui.Position.toObject(includeInstance, f),
    size: (f = msg.getSize()) && proto.ui.Size.toObject(includeInstance, f),
    padding: jspb.Message.getFieldWithDefault(msg, 4, ""),
    margin: jspb.Message.getFieldWithDefault(msg, 5, ""),
    bgColor: jspb.Message.getFieldWithDefault(msg, 6, ""),
    textColor: jspb.Message.getFieldWithDefault(msg, 7, ""),
    border: jspb.Message.getFieldWithDefault(msg, 8, ""),
    rounded: jspb.Message.getFieldWithDefault(msg, 9, ""),
    shadow: jspb.Message.getFieldWithDefault(msg, 10, ""),
    gap: jspb.Message.getFieldWithDefault(msg, 11, ""),
    scrollable: jspb.Message.getBooleanFieldWithDefault(msg, 12, false),
    customClass: jspb.Message.getFieldWithDefault(msg, 13, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ui.Style}
 */
proto.ui.Style.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ui.Style;
  return proto.ui.Style.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ui.Style} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ui.Style}
 */
proto.ui.Style.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.ui.LayoutType} */ (reader.readEnum());
      msg.setLayout(value);
      break;
    case 2:
      var value = new proto.ui.Position;
      reader.readMessage(value,proto.ui.Position.deserializeBinaryFromReader);
      msg.setPosition(value);
      break;
    case 3:
      var value = new proto.ui.Size;
      reader.readMessage(value,proto.ui.Size.deserializeBinaryFromReader);
      msg.setSize(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setPadding(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setMargin(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setBgColor(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setTextColor(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setBorder(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setRounded(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setShadow(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setGap(value);
      break;
    case 12:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setScrollable(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setCustomClass(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ui.Style.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ui.Style.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ui.Style} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ui.Style.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLayout();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getPosition();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.ui.Position.serializeBinaryToWriter
    );
  }
  f = message.getSize();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.ui.Size.serializeBinaryToWriter
    );
  }
  f = message.getPadding();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getMargin();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getBgColor();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getTextColor();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getBorder();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getRounded();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getShadow();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getGap();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
  f = message.getScrollable();
  if (f) {
    writer.writeBool(
      12,
      f
    );
  }
  f = message.getCustomClass();
  if (f.length > 0) {
    writer.writeString(
      13,
      f
    );
  }
};


/**
 * optional LayoutType layout = 1;
 * @return {!proto.ui.LayoutType}
 */
proto.ui.Style.prototype.getLayout = function() {
  return /** @type {!proto.ui.LayoutType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.ui.LayoutType} value
 * @return {!proto.ui.Style} returns this
 */
proto.ui.Style.prototype.setLayout = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional Position position = 2;
 * @return {?proto.ui.Position}
 */
proto.ui.Style.prototype.getPosition = function() {
  return /** @type{?proto.ui.Position} */ (
    jspb.Message.getWrapperField(this, proto.ui.Position, 2));
};


/**
 * @param {?proto.ui.Position|undefined} value
 * @return {!proto.ui.Style} returns this
*/
proto.ui.Style.prototype.setPosition = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ui.Style} returns this
 */
proto.ui.Style.prototype.clearPosition = function() {
  return this.setPosition(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ui.Style.prototype.hasPosition = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Size size = 3;
 * @return {?proto.ui.Size}
 */
proto.ui.Style.prototype.getSize = function() {
  return /** @type{?proto.ui.Size} */ (
    jspb.Message.getWrapperField(this, proto.ui.Size, 3));
};


/**
 * @param {?proto.ui.Size|undefined} value
 * @return {!proto.ui.Style} returns this
*/
proto.ui.Style.prototype.setSize = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ui.Style} returns this
 */
proto.ui.Style.prototype.clearSize = function() {
  return this.setSize(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ui.Style.prototype.hasSize = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string padding = 4;
 * @return {string}
 */
proto.ui.Style.prototype.getPadding = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.ui.Style} returns this
 */
proto.ui.Style.prototype.setPadding = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string margin = 5;
 * @return {string}
 */
proto.ui.Style.prototype.getMargin = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.ui.Style} returns this
 */
proto.ui.Style.prototype.setMargin = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string bg_color = 6;
 * @return {string}
 */
proto.ui.Style.prototype.getBgColor = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.ui.Style} returns this
 */
proto.ui.Style.prototype.setBgColor = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string text_color = 7;
 * @return {string}
 */
proto.ui.Style.prototype.getTextColor = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.ui.Style} returns this
 */
proto.ui.Style.prototype.setTextColor = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string border = 8;
 * @return {string}
 */
proto.ui.Style.prototype.getBorder = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.ui.Style} returns this
 */
proto.ui.Style.prototype.setBorder = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string rounded = 9;
 * @return {string}
 */
proto.ui.Style.prototype.getRounded = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.ui.Style} returns this
 */
proto.ui.Style.prototype.setRounded = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional string shadow = 10;
 * @return {string}
 */
proto.ui.Style.prototype.getShadow = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.ui.Style} returns this
 */
proto.ui.Style.prototype.setShadow = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional string gap = 11;
 * @return {string}
 */
proto.ui.Style.prototype.getGap = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.ui.Style} returns this
 */
proto.ui.Style.prototype.setGap = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};


/**
 * optional bool scrollable = 12;
 * @return {boolean}
 */
proto.ui.Style.prototype.getScrollable = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 12, false));
};


/**
 * @param {boolean} value
 * @return {!proto.ui.Style} returns this
 */
proto.ui.Style.prototype.setScrollable = function(value) {
  return jspb.Message.setProto3BooleanField(this, 12, value);
};


/**
 * optional string custom_class = 13;
 * @return {string}
 */
proto.ui.Style.prototype.getCustomClass = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/**
 * @param {string} value
 * @return {!proto.ui.Style} returns this
 */
proto.ui.Style.prototype.setCustomClass = function(value) {
  return jspb.Message.setProto3StringField(this, 13, value);
};


