// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: protos/page.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ======================
// Component types
// ======================
type ComponentType int32

const (
	ComponentType_UNKNOWN    ComponentType = 0
	ComponentType_TEXT       ComponentType = 1
	ComponentType_BUTTON     ComponentType = 2
	ComponentType_INPUT      ComponentType = 3
	ComponentType_NODE_GRAPH ComponentType = 4 // Debate graph widget
	ComponentType_CHAT       ComponentType = 5 // Chat window
	ComponentType_IMAGE      ComponentType = 6
	ComponentType_LIST       ComponentType = 7
	ComponentType_CONTAINER  ComponentType = 8
	ComponentType_MODAL      ComponentType = 9
)

// Enum value maps for ComponentType.
var (
	ComponentType_name = map[int32]string{
		0: "UNKNOWN",
		1: "TEXT",
		2: "BUTTON",
		3: "INPUT",
		4: "NODE_GRAPH",
		5: "CHAT",
		6: "IMAGE",
		7: "LIST",
		8: "CONTAINER",
		9: "MODAL",
	}
	ComponentType_value = map[string]int32{
		"UNKNOWN":    0,
		"TEXT":       1,
		"BUTTON":     2,
		"INPUT":      3,
		"NODE_GRAPH": 4,
		"CHAT":       5,
		"IMAGE":      6,
		"LIST":       7,
		"CONTAINER":  8,
		"MODAL":      9,
	}
)

func (x ComponentType) Enum() *ComponentType {
	p := new(ComponentType)
	*p = x
	return p
}

func (x ComponentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ComponentType) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_page_proto_enumTypes[0].Descriptor()
}

func (ComponentType) Type() protoreflect.EnumType {
	return &file_protos_page_proto_enumTypes[0]
}

func (x ComponentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ComponentType.Descriptor instead.
func (ComponentType) EnumDescriptor() ([]byte, []int) {
	return file_protos_page_proto_rawDescGZIP(), []int{0}
}

// ======================
// Layout, position, size
// ======================
type LayoutType int32

const (
	LayoutType_ABSOLUTE LayoutType = 0
	LayoutType_FLEX_ROW LayoutType = 1
	LayoutType_FLEX_COL LayoutType = 2
	LayoutType_GRID     LayoutType = 3
)

// Enum value maps for LayoutType.
var (
	LayoutType_name = map[int32]string{
		0: "ABSOLUTE",
		1: "FLEX_ROW",
		2: "FLEX_COL",
		3: "GRID",
	}
	LayoutType_value = map[string]int32{
		"ABSOLUTE": 0,
		"FLEX_ROW": 1,
		"FLEX_COL": 2,
		"GRID":     3,
	}
)

func (x LayoutType) Enum() *LayoutType {
	p := new(LayoutType)
	*p = x
	return p
}

func (x LayoutType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LayoutType) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_page_proto_enumTypes[1].Descriptor()
}

func (LayoutType) Type() protoreflect.EnumType {
	return &file_protos_page_proto_enumTypes[1]
}

func (x LayoutType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LayoutType.Descriptor instead.
func (LayoutType) EnumDescriptor() ([]byte, []int) {
	return file_protos_page_proto_rawDescGZIP(), []int{1}
}

// ======================
// Root Page definition
// ======================
type Page struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageId        string                 `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"` // Unique page identifier
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`                 // Page title
	Components    []*Component           `protobuf:"bytes,3,rep,name=components,proto3" json:"components,omitempty"`       // Top-level components
	Theme         *Theme                 `protobuf:"bytes,4,opt,name=theme,proto3" json:"theme,omitempty"`                 // Optional theme info
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Page) Reset() {
	*x = Page{}
	mi := &file_protos_page_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_protos_page_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_protos_page_proto_rawDescGZIP(), []int{0}
}

func (x *Page) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *Page) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Page) GetComponents() []*Component {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *Page) GetTheme() *Theme {
	if x != nil {
		return x.Theme
	}
	return nil
}

// ======================
// Component definition
// ======================
type Component struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                   // Unique component ID
	Type          ComponentType          `protobuf:"varint,2,opt,name=type,proto3,enum=debate.ComponentType" json:"type,omitempty"`                                                    // Predefined component type
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`                                                                               // Optional label/text
	Children      []*Component           `protobuf:"bytes,4,rep,name=children,proto3" json:"children,omitempty"`                                                                       // Nested components
	Style         *Style                 `protobuf:"bytes,5,opt,name=style,proto3" json:"style,omitempty"`                                                                             // Styling & layout info
	Events        map[string]string      `protobuf:"bytes,6,rep,name=events,proto3" json:"events,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Event name → action ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Component) Reset() {
	*x = Component{}
	mi := &file_protos_page_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Component) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Component) ProtoMessage() {}

func (x *Component) ProtoReflect() protoreflect.Message {
	mi := &file_protos_page_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Component.ProtoReflect.Descriptor instead.
func (*Component) Descriptor() ([]byte, []int) {
	return file_protos_page_proto_rawDescGZIP(), []int{1}
}

func (x *Component) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Component) GetType() ComponentType {
	if x != nil {
		return x.Type
	}
	return ComponentType_UNKNOWN
}

func (x *Component) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Component) GetChildren() []*Component {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *Component) GetStyle() *Style {
	if x != nil {
		return x.Style
	}
	return nil
}

func (x *Component) GetEvents() map[string]string {
	if x != nil {
		return x.Events
	}
	return nil
}

// ======================
// Styling information
// ======================
type Style struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Layout        LayoutType             `protobuf:"varint,1,opt,name=layout,proto3,enum=debate.LayoutType" json:"layout,omitempty"`       // flex/grid/absolute/etc.
	Position      *Position              `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`                           // For absolute/fixed layout
	Size          *Size                  `protobuf:"bytes,3,opt,name=size,proto3" json:"size,omitempty"`                                   // Width & height
	Padding       string                 `protobuf:"bytes,4,opt,name=padding,proto3" json:"padding,omitempty"`                             // Tailwind utility (e.g., "p-4")
	Margin        string                 `protobuf:"bytes,5,opt,name=margin,proto3" json:"margin,omitempty"`                               // Tailwind utility (e.g., "m-2")
	BgColor       string                 `protobuf:"bytes,6,opt,name=bg_color,json=bgColor,proto3" json:"bg_color,omitempty"`              // Tailwind utility (e.g., "bg-blue-500")
	TextColor     string                 `protobuf:"bytes,7,opt,name=text_color,json=textColor,proto3" json:"text_color,omitempty"`        // Tailwind utility (e.g., "text-white")
	Border        string                 `protobuf:"bytes,8,opt,name=border,proto3" json:"border,omitempty"`                               // Tailwind border utility
	Rounded       string                 `protobuf:"bytes,9,opt,name=rounded,proto3" json:"rounded,omitempty"`                             // Tailwind rounded corners
	Shadow        string                 `protobuf:"bytes,10,opt,name=shadow,proto3" json:"shadow,omitempty"`                              // Tailwind shadow class
	Gap           string                 `protobuf:"bytes,11,opt,name=gap,proto3" json:"gap,omitempty"`                                    // Tailwind gap class for children
	Scrollable    bool                   `protobuf:"varint,12,opt,name=scrollable,proto3" json:"scrollable,omitempty"`                     // Allow scroll if content overflows
	CustomClass   string                 `protobuf:"bytes,13,opt,name=custom_class,json=customClass,proto3" json:"custom_class,omitempty"` // Any extra Tailwind class(es)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Style) Reset() {
	*x = Style{}
	mi := &file_protos_page_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Style) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Style) ProtoMessage() {}

func (x *Style) ProtoReflect() protoreflect.Message {
	mi := &file_protos_page_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Style.ProtoReflect.Descriptor instead.
func (*Style) Descriptor() ([]byte, []int) {
	return file_protos_page_proto_rawDescGZIP(), []int{2}
}

func (x *Style) GetLayout() LayoutType {
	if x != nil {
		return x.Layout
	}
	return LayoutType_ABSOLUTE
}

func (x *Style) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Style) GetSize() *Size {
	if x != nil {
		return x.Size
	}
	return nil
}

func (x *Style) GetPadding() string {
	if x != nil {
		return x.Padding
	}
	return ""
}

func (x *Style) GetMargin() string {
	if x != nil {
		return x.Margin
	}
	return ""
}

func (x *Style) GetBgColor() string {
	if x != nil {
		return x.BgColor
	}
	return ""
}

func (x *Style) GetTextColor() string {
	if x != nil {
		return x.TextColor
	}
	return ""
}

func (x *Style) GetBorder() string {
	if x != nil {
		return x.Border
	}
	return ""
}

func (x *Style) GetRounded() string {
	if x != nil {
		return x.Rounded
	}
	return ""
}

func (x *Style) GetShadow() string {
	if x != nil {
		return x.Shadow
	}
	return ""
}

func (x *Style) GetGap() string {
	if x != nil {
		return x.Gap
	}
	return ""
}

func (x *Style) GetScrollable() bool {
	if x != nil {
		return x.Scrollable
	}
	return false
}

func (x *Style) GetCustomClass() string {
	if x != nil {
		return x.CustomClass
	}
	return ""
}

type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"` // px or % depending on renderer
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Unit          string                 `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"` // "px", "%", "rem"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_protos_page_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_protos_page_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_protos_page_proto_rawDescGZIP(), []int{3}
}

func (x *Position) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Position) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Position) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

type Size struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         string                 `protobuf:"bytes,1,opt,name=width,proto3" json:"width,omitempty"`   // Tailwind width class or custom
	Height        string                 `protobuf:"bytes,2,opt,name=height,proto3" json:"height,omitempty"` // Tailwind height class or custom
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Size) Reset() {
	*x = Size{}
	mi := &file_protos_page_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Size) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Size) ProtoMessage() {}

func (x *Size) ProtoReflect() protoreflect.Message {
	mi := &file_protos_page_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Size.ProtoReflect.Descriptor instead.
func (*Size) Descriptor() ([]byte, []int) {
	return file_protos_page_proto_rawDescGZIP(), []int{4}
}

func (x *Size) GetWidth() string {
	if x != nil {
		return x.Width
	}
	return ""
}

func (x *Size) GetHeight() string {
	if x != nil {
		return x.Height
	}
	return ""
}

// ======================
// Theme (optional)
// ======================
type Theme struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PrimaryColor   string                 `protobuf:"bytes,1,opt,name=primary_color,json=primaryColor,proto3" json:"primary_color,omitempty"` // Tailwind-compatible color class
	SecondaryColor string                 `protobuf:"bytes,2,opt,name=secondary_color,json=secondaryColor,proto3" json:"secondary_color,omitempty"`
	FontFamily     string                 `protobuf:"bytes,3,opt,name=font_family,json=fontFamily,proto3" json:"font_family,omitempty"` // e.g., "font-sans"
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Theme) Reset() {
	*x = Theme{}
	mi := &file_protos_page_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Theme) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Theme) ProtoMessage() {}

func (x *Theme) ProtoReflect() protoreflect.Message {
	mi := &file_protos_page_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Theme.ProtoReflect.Descriptor instead.
func (*Theme) Descriptor() ([]byte, []int) {
	return file_protos_page_proto_rawDescGZIP(), []int{5}
}

func (x *Theme) GetPrimaryColor() string {
	if x != nil {
		return x.PrimaryColor
	}
	return ""
}

func (x *Theme) GetSecondaryColor() string {
	if x != nil {
		return x.SecondaryColor
	}
	return ""
}

func (x *Theme) GetFontFamily() string {
	if x != nil {
		return x.FontFamily
	}
	return ""
}

var File_protos_page_proto protoreflect.FileDescriptor

const file_protos_page_proto_rawDesc = "" +
	"\n" +
	"\x11protos/page.proto\x12\x06debate\"\x8d\x01\n" +
	"\x04Page\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x121\n" +
	"\n" +
	"components\x18\x03 \x03(\v2\x11.debate.ComponentR\n" +
	"components\x12#\n" +
	"\x05theme\x18\x04 \x01(\v2\r.debate.ThemeR\x05theme\"\xa0\x02\n" +
	"\tComponent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x04type\x18\x02 \x01(\x0e2\x15.debate.ComponentTypeR\x04type\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12-\n" +
	"\bchildren\x18\x04 \x03(\v2\x11.debate.ComponentR\bchildren\x12#\n" +
	"\x05style\x18\x05 \x01(\v2\r.debate.StyleR\x05style\x125\n" +
	"\x06events\x18\x06 \x03(\v2\x1d.debate.Component.EventsEntryR\x06events\x1a9\n" +
	"\vEventsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8e\x03\n" +
	"\x05Style\x12*\n" +
	"\x06layout\x18\x01 \x01(\x0e2\x12.debate.LayoutTypeR\x06layout\x12,\n" +
	"\bposition\x18\x02 \x01(\v2\x10.debate.PositionR\bposition\x12 \n" +
	"\x04size\x18\x03 \x01(\v2\f.debate.SizeR\x04size\x12\x18\n" +
	"\apadding\x18\x04 \x01(\tR\apadding\x12\x16\n" +
	"\x06margin\x18\x05 \x01(\tR\x06margin\x12\x19\n" +
	"\bbg_color\x18\x06 \x01(\tR\abgColor\x12\x1d\n" +
	"\n" +
	"text_color\x18\a \x01(\tR\ttextColor\x12\x16\n" +
	"\x06border\x18\b \x01(\tR\x06border\x12\x18\n" +
	"\arounded\x18\t \x01(\tR\arounded\x12\x16\n" +
	"\x06shadow\x18\n" +
	" \x01(\tR\x06shadow\x12\x10\n" +
	"\x03gap\x18\v \x01(\tR\x03gap\x12\x1e\n" +
	"\n" +
	"scrollable\x18\f \x01(\bR\n" +
	"scrollable\x12!\n" +
	"\fcustom_class\x18\r \x01(\tR\vcustomClass\":\n" +
	"\bPosition\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\"4\n" +
	"\x04Size\x12\x14\n" +
	"\x05width\x18\x01 \x01(\tR\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\tR\x06height\"v\n" +
	"\x05Theme\x12#\n" +
	"\rprimary_color\x18\x01 \x01(\tR\fprimaryColor\x12'\n" +
	"\x0fsecondary_color\x18\x02 \x01(\tR\x0esecondaryColor\x12\x1f\n" +
	"\vfont_family\x18\x03 \x01(\tR\n" +
	"fontFamily*\x86\x01\n" +
	"\rComponentType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\b\n" +
	"\x04TEXT\x10\x01\x12\n" +
	"\n" +
	"\x06BUTTON\x10\x02\x12\t\n" +
	"\x05INPUT\x10\x03\x12\x0e\n" +
	"\n" +
	"NODE_GRAPH\x10\x04\x12\b\n" +
	"\x04CHAT\x10\x05\x12\t\n" +
	"\x05IMAGE\x10\x06\x12\b\n" +
	"\x04LIST\x10\a\x12\r\n" +
	"\tCONTAINER\x10\b\x12\t\n" +
	"\x05MODAL\x10\t*@\n" +
	"\n" +
	"LayoutType\x12\f\n" +
	"\bABSOLUTE\x10\x00\x12\f\n" +
	"\bFLEX_ROW\x10\x01\x12\f\n" +
	"\bFLEX_COL\x10\x02\x12\b\n" +
	"\x04GRID\x10\x03B&Z$debate/go_page_builder/protos;protosb\x06proto3"

var (
	file_protos_page_proto_rawDescOnce sync.Once
	file_protos_page_proto_rawDescData []byte
)

func file_protos_page_proto_rawDescGZIP() []byte {
	file_protos_page_proto_rawDescOnce.Do(func() {
		file_protos_page_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_page_proto_rawDesc), len(file_protos_page_proto_rawDesc)))
	})
	return file_protos_page_proto_rawDescData
}

var file_protos_page_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_protos_page_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_protos_page_proto_goTypes = []any{
	(ComponentType)(0), // 0: debate.ComponentType
	(LayoutType)(0),    // 1: debate.LayoutType
	(*Page)(nil),       // 2: debate.Page
	(*Component)(nil),  // 3: debate.Component
	(*Style)(nil),      // 4: debate.Style
	(*Position)(nil),   // 5: debate.Position
	(*Size)(nil),       // 6: debate.Size
	(*Theme)(nil),      // 7: debate.Theme
	nil,                // 8: debate.Component.EventsEntry
}
var file_protos_page_proto_depIdxs = []int32{
	3, // 0: debate.Page.components:type_name -> debate.Component
	7, // 1: debate.Page.theme:type_name -> debate.Theme
	0, // 2: debate.Component.type:type_name -> debate.ComponentType
	3, // 3: debate.Component.children:type_name -> debate.Component
	4, // 4: debate.Component.style:type_name -> debate.Style
	8, // 5: debate.Component.events:type_name -> debate.Component.EventsEntry
	1, // 6: debate.Style.layout:type_name -> debate.LayoutType
	5, // 7: debate.Style.position:type_name -> debate.Position
	6, // 8: debate.Style.size:type_name -> debate.Size
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_protos_page_proto_init() }
func file_protos_page_proto_init() {
	if File_protos_page_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_page_proto_rawDesc), len(file_protos_page_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_page_proto_goTypes,
		DependencyIndexes: file_protos_page_proto_depIdxs,
		EnumInfos:         file_protos_page_proto_enumTypes,
		MessageInfos:      file_protos_page_proto_msgTypes,
	}.Build()
	File_protos_page_proto = out.File
	file_protos_page_proto_goTypes = nil
	file_protos_page_proto_depIdxs = nil
}
