/**
 * @fileoverview gRPC-Web generated client stub for test
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.20.1
// source: data.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.test = require('./data_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.test.DataServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.test.DataServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.test.MyData,
 *   !proto.test.MyData>}
 */
const methodDescriptor_DataService_SendData = new grpc.web.MethodDescriptor(
  '/test.DataService/SendData',
  grpc.web.MethodType.UNARY,
  proto.test.MyData,
  proto.test.MyData,
  /**
   * @param {!proto.test.MyData} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.test.MyData.deserializeBinary
);


/**
 * @param {!proto.test.MyData} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.test.MyData)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.test.MyData>|undefined}
 *     The XHR Node Readable Stream
 */
proto.test.DataServiceClient.prototype.sendData =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/test.DataService/SendData',
      request,
      metadata || {},
      methodDescriptor_DataService_SendData,
      callback);
};


/**
 * @param {!proto.test.MyData} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.test.MyData>}
 *     Promise that resolves to the response
 */
proto.test.DataServicePromiseClient.prototype.sendData =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/test.DataService/SendData',
      request,
      metadata || {},
      methodDescriptor_DataService_SendData);
};


module.exports = proto.test;

