/**
 * @fileoverview gRPC-Web generated client stub for test
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.20.1
// source: data.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as data_pb from './data_pb'; // proto import: "data.proto"


export class DataServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorSendData = new grpcWeb.MethodDescriptor(
    '/test.DataService/SendData',
    grpcWeb.MethodType.UNARY,
    data_pb.MyData,
    data_pb.MyData,
    (request: data_pb.MyData) => {
      return request.serializeBinary();
    },
    data_pb.MyData.deserializeBinary
  );

  sendData(
    request: data_pb.MyData,
    metadata?: grpcWeb.Metadata | null): Promise<data_pb.MyData>;

  sendData(
    request: data_pb.MyData,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: data_pb.MyData) => void): grpcWeb.ClientReadableStream<data_pb.MyData>;

  sendData(
    request: data_pb.MyData,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: data_pb.MyData) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/test.DataService/SendData',
        request,
        metadata || {},
        this.methodDescriptorSendData,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/test.DataService/SendData',
    request,
    metadata || {},
    this.methodDescriptorSendData);
  }

}

