// @generated by protoc-gen-es v2.6.3
// @generated from file data.proto (package test, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file data.proto.
 */
export declare const file_data: GenFile;

/**
 * Simple message to send between client and server
 *
 * @generated from message test.MyData
 */
export declare type MyData = Message<"test.MyData"> & {
  /**
   * Name of the user
   *
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * Game score or points
   *
   * @generated from field: int32 score = 2;
   */
  score: number;
};

/**
 * Describes the message test.MyData.
 * Use `create(MyDataSchema)` to create a new message.
 */
export declare const MyDataSchema: GenMessage<MyData>;

/**
 * Simple gRPC service for testing
 *
 * @generated from service test.DataService
 */
export declare const DataService: GenService<{
  /**
   * @generated from rpc test.DataService.SendData
   */
  sendData: {
    methodKind: "unary";
    input: typeof MyDataSchema;
    output: typeof MyDataSchema;
  },
}>;

