// @generated by protoc-gen-es v2.6.2
// @generated from file event.proto (package debate, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file event.proto.
 */
export const file_event = /*@__PURE__*/
  fileDesc("CgtldmVudC5wcm90bxIGZGViYXRlIrsBCgdVSUV2ZW50EhAKCGV2ZW50X2lkGAEgASgJEhQKDGNvbXBvbmVudF9pZBgCIAEoCRIfCgR0eXBlGAMgASgOMhEuZGViYXRlLkV2ZW50VHlwZRIRCgl0aW1lc3RhbXAYBCABKAMSJwoEZGF0YRgFIAMoCzIZLmRlYmF0ZS5VSUV2ZW50LkRhdGFFbnRyeRorCglEYXRhRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4ASqKAQoJRXZlbnRUeXBlEgsKB1VOS05PV04QABIJCgVDTElDSxABEhAKDElOUFVUX0NIQU5HRRACEg8KC0ZPUk1fU1VCTUlUEAMSDgoKTk9ERV9BRERFRBAEEhAKDE5PREVfUkVNT1ZFRBAFEg4KCkVER0VfQURERUQQBhIQCgxFREdFX1JFTU9WRUQQB2IGcHJvdG8z");

/**
 * Describes the message debate.UIEvent.
 * Use `create(UIEventSchema)` to create a new message.
 */
export const UIEventSchema = /*@__PURE__*/
  messageDesc(file_event, 0);

/**
 * Describes the enum debate.EventType.
 */
export const EventTypeSchema = /*@__PURE__*/
  enumDesc(file_event, 0);

/**
 * List of possible event types
 *
 * @generated from enum debate.EventType
 */
export const EventType = /*@__PURE__*/
  tsEnum(EventTypeSchema);

