// @generated by protoc-gen-es v2.6.3
// @generated from file hello.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file hello.proto.
 */
export declare const file_hello: GenFile;

/**
 * @generated from message HelloRequest
 */
export declare type HelloRequest = Message<"HelloRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message HelloRequest.
 * Use `create(HelloRequestSchema)` to create a new message.
 */
export declare const HelloRequestSchema: GenMessage<HelloRequest>;

/**
 * @generated from message HelloReply
 */
export declare type HelloReply = Message<"HelloReply"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message HelloReply.
 * Use `create(HelloReplySchema)` to create a new message.
 */
export declare const HelloReplySchema: GenMessage<HelloReply>;

/**
 * @generated from service Greeter
 */
export declare const Greeter: GenService<{
  /**
   * @generated from rpc Greeter.SayHello
   */
  sayHello: {
    methodKind: "unary";
    input: typeof HelloRequestSchema;
    output: typeof HelloReplySchema;
  },
}>;

